/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package skinfold;

public class App {

    /// <summary>
    /// The main entry point for the application.
    /// </summary>
    public static void main(String[] args) {
        new Calculator().takeAllMeasurements();
    }
}
